version: '3.7'

# 컴퓨터들
services:

  #  컴퓨터 이름
  my-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      - ./email.js:/myfolder/phone.js    
      # - ./src:/myfolder/src => 폴더 전체를 공유
    ports:
      - 4000:4000 

  #  컴퓨터 이름
  my_database:
    image: mongo:5
    ports:
      - 27017:27017 