version: '3.7'

# 컴퓨터들
services:
    # 컴퓨터이름
    phone-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/myfolder/index.js
            - ./phone.js:/myfolder/phone.js
        ports:
            - 4000:4000
    # 컴퓨터이름
    phone-database:
        image: mongo:5
        ports:
            - 27017:27017
