version: '3.7'

services:
    myserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000

    mongodb:
        image: mongo:5
        ports:
            - 27017:27017
