version: "1.0"

services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./index.js:/day10/index.js
      - ./token.js:/day10/token.js
      - ./phone.js:/day10/phone.js

  token-database:
    image: mongo:5
    ports:
      - 27017:27017
