version: "1.0"

# 컴퓨터
services:
  # 서버
  express_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  # mongoDB 서버
  mongo_database:
    image: mongo:5
    ports:
      - 27017:27017
