version: "3.7"

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./phone.js:/myfolder/phone.js
    ports:
      - 4000:4000

  # 컴퓨터이름
  my-database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
