version: '3.7'

services:
  my-nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # 볼륨 공유
    volumes:
      - ./src:/main-project/src
    # 포트포워딩
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker
    environment:
      - TZ=Asia/Seoul

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  # 컴퓨터이름
  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
