version: "1.0.0"

services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./index.js:/Mini-Project/index.js
      - ./srcs/:/Mini-Project/srcs/
      - ./models/:/Mini-Project/models/
      - ./swagger/:/Mini-Project/swagger/
      - ./controllers/:/Mini-Project/controllers/

  mongodb:
    image: mongo:5
    ports:
      - 27017:27017
