version: '3.7'

services:
  my-nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # 볼륨 공유
    volumes:
      - ./src:/day18/src
    # 포트포워딩
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myErdDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
